name: Hello World Workflow

# Trigger the workflow on push or pull request to the main branch
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World
      run: echo "Hello World"
